name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v4
    
    - name: Setup SSH Deploy Key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
    
    - name: Test SSH connection
      run: |
        ssh -T git@github.com || true  # Игнорируем ошибку выхода
    
    - name: Clone target repository via SSH
      run: |
        git clone git@github.com:rand0mRU/rand0mRU.github.io.git gh-pages-repo
    
    - name: Copy files
      run: |
        mkdir -p gh-pages-repo/comport
        cp -r ./*.html ./*.md ./*.js gh-pages-repo/comport/
    
    - name: Commit and push
      run: |
        cd gh-pages-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy HTML: ${{ github.sha }}" || echo "No changes to commit"
        git push